vagrant/sample_app/config/routes.rb
Rails.application.routes.draw do
  get 'posts/new' => 'posts#new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/top' => 'root#top'

  post '/posts' => 'posts#create'

  get '/posts/:id' => 'posts#show', as: 'post'
   # /posts 」というURLでpostsコントローラのindexアクションが実行され「index.html.erb」の内容がビューとして表示されます。
  # /posts/1 や /posts/3 に該当する
  get '/posts' => 'posts#index'

  get '/posts/:id/edit' => 'posts#edit', as: 'edit_post'

  patch '/posts/:id' => 'posts#update', as:'update_post'
  # 削除機能の追加
  delete '/posts/:id' => 'posts#destroy', as: 'destroy_post'

end

vagrant/sample_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

vagrant/sample_app/app/models/post.rb
class Post < ApplicationRecord
	attachment :image
end

vagrant/sample_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

vagrant/sample_app/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
  	# からのモデルをビューへ渡す
  	@post = Post.new
  end

  def create
  	#ストロングパラメーターを使用
  	post = Post.new(post_params)
  	#DBへ保存する
  	post.save
  	#新規投稿画面へリダイレクト
  	redirect_to post_path(post.id)
  end

  def index
  	@posts = Post.all
  end

  def show
  	@post = Post.find(params[:id])
  end

  def edit
        @post = Post.find(params[:id])
  end

  def update
  	@post = Post.new(post_params)
  	@post.update(post_params)
  	redirect_to post_path(@post.id)
  end

  def destroy
  	# データ（レコード）を１件取得
  	@post = Post.find(params[:id])
  	# レコードをDBから削除
  	@post.destroy
  	# post一覧画面へリダイレクト
  	redirect_to posts_path
  end


  # privateは一種の境界線で、「ここから下はcontrollerの中でしか呼び出せません」という意味。
  # privateはControllerファイルの一番下のendのすぐ上に書いて下さい。
  private

	def post_params
        params.require(:post).permit(:title, :body, :image)
    end
end

vagrant/sample_app/app/controllers/root_controller.rb
class RootController < ApplicationController
	def top
		
	end
end

vagrant/sample_app/app/helpers/application_helper.rb
module ApplicationHelper
end

vagrant/sample_app/app/helpers/posts_helper.rb
module PostsHelper
end

vagrant/sample_app/app/helpers/root_helper.rb
module RootHelper
end

vagrant/sample_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

vagrant/sample_app/app/views/posts/edit.html.erb
<h1>編集画面</h1>
<%= form_for(@post) do |f| %>
    <h4>タイトル</h4>
    <%= f.text_field :title %>
    <h4>本文</h4>
    <%= f.text_area :body %>
    <%= f.submit '保存' %>
<% end %>

vagrant/sample_app/app/views/posts/index.html.erb
<h1>投稿一覧</h1>
<% @posts.each do |post| %>
	<p>タイトル</p>
	<span>
		<%=link_to post.title, post_path(post.id) %>
	</span>
	<p>画像</p>
	<%= attachment_image_tag post, :image, :fill, 100, 100, format: 'jpag' %>
<% end %>

vagrant/sample_app/app/views/posts/new.html.erb
<h1>新規投稿</h1>
<!-- from_for部分 -->
<%= form_for(@post) do |f| %>

	<h4>タイトル</h4>
	<%= f.text_field :title %>

	<h4>本文</h4>
	<%= f.text_area :body %>

	<!-- 画像投稿機能追加 -->
	<h4>画像</h4>
	<%= f.attachment_field :image%>
	

	<%= f.submit '投稿' %>

<% end %>

vagrant/sample_app/app/views/posts/show.html.erb
<h2>タイトル</h2>
<%= @post.title %>
<h2>本文</h2>
<%= @post.body %>
<h2>画像</h2>
<%= attachment_image_tag @post, :image, :fill, 300, 300, format: 'jpeg' %>

<%= link_to "編集", edit_post_path(@post.id), class: "btn edit-btn" %>
<%= link_to "削除", destroy_post_path(@post.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>


<!-- 編集ページへのリンク -->
<%= link_to "編集", edit_post_path(@post.id) %>

vagrant/sample_app/app/views/root/top.html.erb
<h1>ここはTopページです。</h1>